/* V2 MAQUETTE. Les produits et textes ci-dessous sont des exemples. */
const PRODUITS=[
{id:'bleu',name:'Bleu de poche',category:'Dessins & peintures',subtitle:'Gouache, encre et papier',story:'Texte de démonstration destiné à montrer la place de la véritable histoire de la pièce.',journey:'Né à l’atelier → peint → signé → prêt à partir.',note:'une petite trace laissée au crayon.',price:'39 €',dimensions:'24 × 30 cm',materials:'Gouache, encre, papier',type:'Pièce unique',delivery:'Livraison incluse',status:'available',isNew:true,variant:'blue-landscape',paymentLink:'#'},
{id:'lettre',name:'Lettre à personne',category:'Collages & papier',subtitle:'Papier ancien et fil',story:'Des papiers se rencontrent sur la table. Le texte final racontera la vraie création et ses matières.',journey:'Papiers trouvés → triés → assemblés → nouvelle histoire.',note:'les papiers aussi ont une mémoire.',price:'32 €',dimensions:'21 × 29,7 cm',materials:'Papiers, fil, colle',type:'Pièce unique',delivery:'Livraison incluse',status:'available',isNew:true,variant:'letter',paymentLink:'#'},
{id:'souffleur',name:'Petit Souffleur',category:'Sculptures',subtitle:'Personnage d’atelier · exemple',story:'Une place réservée à l’histoire du personnage, à son caractère et au détail qui donnera envie de l’adopter.',journey:'Modelé → séché → peint → assemblé à la main à Bailleul.',note:'il paraît qu’il souffle juste avant de partir.',price:'39 €',dimensions:'env. 18 cm',materials:'Argile autodurcissante, papier, acrylique',type:'Petite série',delivery:'Livraison incluse',status:'available',isNew:true,variant:'leaf-lady',paymentLink:'#'},
{id:'gardien',name:'Petit gardien',category:'Sculptures',subtitle:'Bois trouvé · exemple',story:'Un exemple de pièce fabriquée à partir d’un matériau qui avait déjà une vie avant de passer par l’atelier.',journey:'Trouvé → nettoyé → transformé → prêt pour une nouvelle étagère.',note:'tenir compagnie est déjà un métier.',price:'45 €',dimensions:'27 × 8 × 7 cm',materials:'Bois, cire, graphite',type:'Pièce unique',delivery:'Livraison incluse',status:'available',variant:'little-guard',paymentLink:'#'},
{id:'soleil',name:'Le soleil qui reste',category:'Collages & papier',subtitle:'Collage · exemple',story:'Cette histoire est volontairement factice. Elle montre comment une création pourra être racontée sans transformer la boutique en catalogue.',journey:'Chutes de papier → composition → collage → signature.',note:'rien ne se perd vraiment sur la table.',price:'35 €',dimensions:'30 × 30 cm',materials:'Carton, papiers, pastel',type:'Pièce unique',delivery:'Livraison incluse',status:'adopted',variant:'sun-collage',paymentLink:'#'},
{id:'lampe',name:'La lampe bleue',category:'Objets & mobilier transformés',subtitle:'Objet transformé · exemple',story:'Une lampe chinée, transformée puis remise en scène. La vraie fiche pourra raconter où elle a été trouvée et ce qui a été conservé.',journey:'Chinée → nettoyée → transformée → remise en lumière.',note:'une autre vie, sans effacer la première.',price:'65 €',dimensions:'42 × 18 cm',materials:'Métal, tissu, peinture',type:'Pièce unique',delivery:'Livraison incluse',status:'available',variant:'blue-lamp',paymentLink:'#'},
{id:'tabouret',name:'Le tabouret vert',category:'Objets & mobilier transformés',subtitle:'Petit mobilier · exemple',story:'Pour le mobilier, le parcours reste poétique mais l’information pratique est immédiate : la pièce vient se chercher à Bailleul.',journey:'Trouvé → décapé → travaillé → prêt pour une nouvelle maison.',note:'les meubles aussi changent de décor.',price:'120 €',dimensions:'44 × 31 × 31 cm',materials:'Bois massif, finition mate',type:'Pièce unique',delivery:'Retrait à Bailleul uniquement',status:'available',variant:'little-guard',paymentLink:'#'}];
let activeFilter='Tout';const grid=document.querySelector('#product-grid'),newGrid=document.querySelector('#new-grid'),story=document.querySelector('#story');
function art(p){return `<div class="art-preview art-${p.variant}" role="img" aria-label="Emplacement visuel pour ${p.name}"></div>`}
function card(p){const sold=p.status!=='available';return `<article class="product-card ${sold?'is-adopted':''}"><button class="product-open" data-id="${p.id}"><div class="product-image">${art(p)}${p.isNew?'<span class="new-tag">nouveau ici</span>':''}${sold?'<span class="adopted-tag">parti vivre ailleurs</span>':''}</div><div class="product-info"><p class="eyebrow">${p.category}</p><h3>${p.name}</h3><p>${p.subtitle}</p></div></button><div class="product-footer"><span class="product-price">${p.price}</span><span class="${sold?'adopted-copy':'adopt-link'}">${sold?'Cette pièce a trouvé sa maison':'Voir son histoire →'}</span></div></article>`}
function bind(){document.querySelectorAll('.product-open').forEach(b=>b.onclick=()=>openStory(PRODUITS.find(p=>p.id===b.dataset.id)))}
function render(){const list=activeFilter==='Tout'?PRODUITS:PRODUITS.filter(p=>p.category===activeFilter);grid.innerHTML=list.map(card).join('');document.querySelector('#filter-count').textContent=`${list.length} pièce${list.length>1?'s':''} visible${list.length>1?'s':''}`;bind()}
function renderNew(){newGrid.innerHTML=PRODUITS.filter(p=>p.isNew).slice(0,3).map(card).join('');bind()}
function openStory(p){document.querySelector('#story-image').innerHTML=art(p);document.querySelector('#story-title').textContent=p.name;document.querySelector('#story-subtitle').textContent=p.subtitle;document.querySelector('#story-price').textContent=p.price;document.querySelector('#story-delivery').textContent=p.delivery;document.querySelector('#story-text').textContent=p.story;document.querySelector('#story-journey').textContent=p.journey;document.querySelector('#story-note').textContent=p.note;document.querySelector('#story-details').innerHTML=`<div><dt>Édition</dt><dd>${p.type}</dd></div><div><dt>Matières</dt><dd>${p.materials}</dd></div><div><dt>Format</dt><dd>${p.dimensions}</dd></div><div><dt>Remise</dt><dd>${p.delivery}</dd></div>`;const adopt=document.querySelector('#story-adopt'),note=document.querySelector('#stripe-note');if(p.status==='available'){adopt.style.display='flex';adopt.href=p.paymentLink;note.textContent='Le lien de paiement réel sera ajouté lors de la mise en vente.'}else{adopt.style.display='none';note.textContent='Cette pièce a trouvé sa maison.'}story.classList.add('is-open');setTimeout(()=>story.scrollIntoView({behavior:'smooth',block:'start'}),20)}
document.querySelector('.story-close').onclick=()=>story.classList.remove('is-open');document.querySelectorAll('.filter-button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-button').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');activeFilter=b.dataset.filter;render()});const menu=document.querySelector('.main-navigation'),toggle=document.querySelector('.menu-toggle');toggle.onclick=()=>{menu.classList.toggle('is-open');toggle.setAttribute('aria-expanded',menu.classList.contains('is-open'))};menu.querySelectorAll('a').forEach(a=>a.onclick=()=>menu.classList.remove('is-open'));const form=document.querySelector('#contact-form');form.onsubmit=e=>{e.preventDefault();document.querySelector('#form-status').hidden=false};renderNew();render();